import { type NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";

const Redirect: NextPage = () => {

  const router = useRouter()
  const { accessToken, userId } = router.query

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {accessToken}
        {userId}
      </main>
    </>
  );
};

export default Redirect;
